---
- name: Include task to create required user
  ansible.builtin.include_tasks:
    file: vagrant.yml

- name: Enable remote login
  ansible.builtin.command:
    cmd: /usr/sbin/systemsetup -setremotelogin on
  become: true
...
