#!/bin/bash
# Export VS Code extensions and settings

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"
EXPORT_DIR="$REPO_DIR/files/exports"
VSCODE_DIR="$HOME/Library/Application Support/Code/User"

# Colors
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m'

mkdir -p "$EXPORT_DIR/vscode"

# Check if VS Code is installed
if ! command -v code &> /dev/null; then
    echo -e "${YELLOW}VS Code not installed or 'code' command not in PATH. Skipping.${NC}"
    echo "To enable: Open VS Code > Cmd+Shift+P > 'Shell Command: Install code command in PATH'"
    exit 0
fi

echo "Exporting VS Code extensions..."
code --list-extensions > "$EXPORT_DIR/vscode/extensions.txt"

# Generate install script
cat > "$EXPORT_DIR/vscode/install-extensions.sh" << 'EOF'
#!/bin/bash
# Install VS Code extensions
# Generated by export-vscode.sh

set -e

echo "Installing VS Code extensions..."

EOF

code --list-extensions | while read ext; do
    echo "code --install-extension \"$ext\" || true" >> "$EXPORT_DIR/vscode/install-extensions.sh"
done

echo "" >> "$EXPORT_DIR/vscode/install-extensions.sh"
echo 'echo "Done installing extensions."' >> "$EXPORT_DIR/vscode/install-extensions.sh"

chmod +x "$EXPORT_DIR/vscode/install-extensions.sh"

# Copy settings if they exist
if [ -f "$VSCODE_DIR/settings.json" ]; then
    echo "Exporting VS Code settings..."
    cp "$VSCODE_DIR/settings.json" "$EXPORT_DIR/vscode/settings.json"
fi

if [ -f "$VSCODE_DIR/keybindings.json" ]; then
    echo "Exporting VS Code keybindings..."
    cp "$VSCODE_DIR/keybindings.json" "$EXPORT_DIR/vscode/keybindings.json"
fi

# Export snippets directory
if [ -d "$VSCODE_DIR/snippets" ]; then
    echo "Exporting VS Code snippets..."
    cp -r "$VSCODE_DIR/snippets" "$EXPORT_DIR/vscode/"
fi

echo ""
echo -e "${GREEN}VS Code export complete: $EXPORT_DIR/vscode/${NC}"
echo "  - extensions.txt ($(wc -l < "$EXPORT_DIR/vscode/extensions.txt" | tr -d ' ') extensions)"
echo "  - install-extensions.sh"
[ -f "$EXPORT_DIR/vscode/settings.json" ] && echo "  - settings.json"
[ -f "$EXPORT_DIR/vscode/keybindings.json" ] && echo "  - keybindings.json"
[ -d "$EXPORT_DIR/vscode/snippets" ] && echo "  - snippets/"
